backend:
  name: github
  branch: main
  repo: shitz/docs-poc
  squash_merges: true

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

# Enable the editorial workflow which translates to a pull request workflow.
publish_mode: editorial_workflow
site_url: https://anapaya-docs-poc.netlify.app/

collections:
- name: basic_tutorials
  label: "Basic Tutorials"
  folder: docs/tutorials-basic
  create: true
  publish: false
  extension: md
  fields:
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown
    - label: Sidebar Position
      name: sidebar_position
      widget: number
      required: false
- name: extra_tutorials
  label: "Extra Tutorials"
  folder: docs/tutorials-extra
  create: true
  publish: false
  extension: md
  fields:
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown
    - label: Sidebar Position
      name: sidebar_position
      widget: number
      required: false
