backend:
  name: git-gateway
  repo: shitz/docs-poc
  branch: main
  identity_url: https://anapaya-docs-poc.netlify.app/.netlify/identity
  gateway_url: https://anapaya-docs-poc.netlify.app/.netlify/git

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

# Enable the editorial workflow which translates to a pull request workflow.
publish_mode: editorial_workflow
site_url: https://anapaya-docs-poc.netlify.app/

collections:
- name: basic_tutorials
  label: "Basic Tutorials"
  folder: docs/tutorial-basics
  create: true
  publish: false
  widget: list
  extension: md
  fields:
    - label: Sidebar Position
      name: sidebar_position
      widget: number
      required: false
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown
- name: extra_tutorials
  label: "Extra Tutorials"
  folder: docs/tutorial-extras
  create: true
  publish: false
  widget: list
  extension: md
  fields:
    - label: Sidebar Position
      name: sidebar_position
      widget: number
      required: false
    - label: Title
      name: title
      widget: string
    - label: Body
      name: body
      widget: markdown

